# For detailed configuration reference, visit:
# https://supabase.com/docs/guides/cli/config

project_id = "FacilityManagerPro"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets]
avatars = { public = false, file_size_limit = "5MiB", allowed_mime_types = ["image/png", "image/jpeg", "image/gif"] }
documents = { public = false, file_size_limit = "10MiB", allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"] }
temp = { public = false, file_size_limit = "100MiB", allowed_mime_types = [] }

[realtime]
enabled = true

[analytics]
enabled = false

[auto_schema]
enabled = false

