-- Eliminar todas las funciones existentes
DROP FUNCTION IF EXISTS get_user_chat_rooms();
DROP FUNCTION IF EXISTS get_user_chat_rooms(OUT room_id UUID, OUT room_name TEXT, OUT room_type TEXT, OUT organization_id UUID, OUT created_at TIMESTAMPTZ, OUT updated_at TIMESTAMPTZ, OUT last_message JSONB, OUT unread_count BIGINT, OUT member_count BIGINT);
DROP FUNCTION IF EXISTS get_chat_messages_v2(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS ensure_chat_membership(UUID, UUID);
DROP FUNCTION IF EXISTS mark_chat_room_as_read(UUID);
DROP FUNCTION IF EXISTS get_org_admins();
DROP FUNCTION IF EXISTS get_chat_messages(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_room_messages(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS fetch_room_messages(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_chat_room_messages_v1(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_chat_room_messages_v2(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS check_chat_room_membership(UUID, UUID);
DROP FUNCTION IF EXISTS check_same_organization(UUID, UUID);
DROP FUNCTION IF EXISTS log_chat_operation(TEXT, TEXT, JSONB);

-- Eliminar todas las políticas existentes
DROP POLICY IF EXISTS "Ver chats de su organización" ON chat_rooms;
DROP POLICY IF EXISTS "Gestionar membresías de su organización" ON chat_room_members;
DROP POLICY IF EXISTS "Gestionar mensajes de sus chats" ON chat_messages;
DROP POLICY IF EXISTS "chat_rooms_policy" ON chat_rooms;
DROP POLICY IF EXISTS "chat_room_members_policy" ON chat_room_members;
DROP POLICY IF EXISTS "chat_messages_policy" ON chat_messages;
DROP POLICY IF EXISTS "Rooms are viewable by organization" ON chat_rooms;
DROP POLICY IF EXISTS "Rooms can be created by authenticated users" ON chat_rooms;
DROP POLICY IF EXISTS "Members are viewable by organization" ON chat_room_members;
DROP POLICY IF EXISTS "Members can be added by organization members" ON chat_room_members;
DROP POLICY IF EXISTS "Members can update their own data" ON chat_room_members;
DROP POLICY IF EXISTS "Messages are viewable by organization" ON chat_messages;
DROP POLICY IF EXISTS "Messages can be created by room members" ON chat_messages;
DROP POLICY IF EXISTS "Messages can be updated by their creators" ON chat_messages;
DROP POLICY IF EXISTS "enable_all_for_members" ON chat_room_members;
DROP POLICY IF EXISTS "enable_all_for_members_messages" ON chat_messages;
DROP POLICY IF EXISTS "members_select" ON chat_room_members;
DROP POLICY IF EXISTS "members_insert" ON chat_room_members;
DROP POLICY IF EXISTS "members_update" ON chat_room_members;
DROP POLICY IF EXISTS "messages_select" ON chat_messages;
DROP POLICY IF EXISTS "messages_insert" ON chat_messages;
DROP POLICY IF EXISTS "messages_update" ON chat_messages;
DROP POLICY IF EXISTS "crm_select" ON chat_room_members;
DROP POLICY IF EXISTS "crm_insert" ON chat_room_members;
DROP POLICY IF EXISTS "crm_update" ON chat_room_members;
DROP POLICY IF EXISTS "cm_select" ON chat_messages;
DROP POLICY IF EXISTS "cm_insert" ON chat_messages;
DROP POLICY IF EXISTS "cm_update" ON chat_messages;
DROP POLICY IF EXISTS "chat_room_members_select" ON chat_room_members;
DROP POLICY IF EXISTS "chat_room_members_insert" ON chat_room_members;
DROP POLICY IF EXISTS "chat_room_members_update" ON chat_room_members;
DROP POLICY IF EXISTS "chat_messages_select" ON chat_messages;
DROP POLICY IF EXISTS "chat_messages_insert" ON chat_messages;
DROP POLICY IF EXISTS "chat_messages_update" ON chat_messages;
DROP POLICY IF EXISTS "Enable read access for users in same organization" ON chat_rooms;
DROP POLICY IF EXISTS "Enable insert for users in same organization" ON chat_rooms;
DROP POLICY IF EXISTS "Enable read for organization members" ON chat_room_members;
DROP POLICY IF EXISTS "Enable insert for organization members" ON chat_room_members;
DROP POLICY IF EXISTS "Enable update for own membership" ON chat_room_members;
DROP POLICY IF EXISTS "Enable read for room members" ON chat_messages;
DROP POLICY IF EXISTS "Enable insert for room members" ON chat_messages;
DROP POLICY IF EXISTS "Enable update for message creators" ON chat_messages; 