-- Primero crear el área
INSERT INTO areas (
    id,
    organization_id,
    name,
    description
)
VALUES (
    'e7ddbbd4-a30f-403c-b219-d9660014a799',
    'e7ddbbd4-a30f-403c-b219-d9660014a799',
    'Área de Limpieza General',
    'Área destinada a las tareas de limpieza y mantenimiento'
)
ON CONFLICT (id) DO NOTHING;

-- Insertar las tareas de limpieza
INSERT INTO tasks (
    organization_id,
    area_id,
    title,
    description,
    status,
    priority,
    type,
    frequency
)
SELECT 
    (SELECT organization_id FROM areas WHERE id = '16853466-b2fd-43d5-998f-9a3ef67568d1'),
    '16853466-b2fd-43d5-998f-9a3ef67568d1',
    title,
    description,
    'pending',
    'medium',
    'cleaning',
    'diario'
FROM (VALUES 
    ('Paso 1', 'SE REALIZA HIGIENE DE MANOS Y SE COLOCA EL EQUIPO DE PROTECCIÓN PERSONAL'),
    ('Paso 2', 'SE CLASIFICA EL AREA SEGUN EL TIPO DE LIMPIEZA PROFUNDA'),
    ('Paso 3', 'SE LIMPIA Y DESINFECTA CON AGUA ENJABONADA, CON WAYPALL EN METODO DE FRICCION Y ARRASTRE'),
    ('Paso 4', 'SE LIMPIA LAS SUPERFICIES HORIZONTALES DEBEMOS LIMPIARLOS CON UN PAÑO EMBEDIDO DE DESINFECTANTES COMO CAMAS, MOBILIARIOS DE MEDICAMENTOS'),
    ('Paso 5', 'SE ENJUAGA CAMA DE PACIENTE CON AGUA Y SE REALIZA METODO DE FRICCION CON WAYPALL'),
    ('Paso 6', 'EL PASILLO INTERNO BARRIDO HUMEDO, LIMPIEZA Y DESINFECCION CON TECNICA ZIGZAG'),
    ('Paso 7', 'SE LIMPIA LAS SUPERFICIES HORIZONTALES DEBEMOS LIMPIARLOS CON UN PAÑO EMBEDIDO DE DESINFECTANTES COMO MESAS, MOBILIARIOS DE MEDICAMENTOS'),
    ('Paso 8', 'LA SOLUCION DESINFECTANTE SE DEBE PREPARAR EN EL MOMENTO DE USO Y DESCARTAR LUEGO DE 24 HORAS'),
    ('Paso 9', 'SE REALIZA HIGIENE DE MANOS Y SE COLOCA EL EQUIPO DE PROTECCIÓN PERSONAL'),
    ('Paso 10', 'SE CLASIFICA EL AREA SEGUN EL TIPO DE LIMPIEZA PROFUNDA'),
    ('Paso 11', 'SE LIMPIA LA UNIDAD DEL PACIENTE CON AGUA ENJABONADA, CON WAYPALL EN METODO DE FRICCION Y ARRASTRE'),
    ('Paso 12', 'SE LIMPIA LAS SUPERFICIES HORIZONTALES DEBEMOS LIMPIARLOS CON UN PAÑO EMBEDIDO DE DESINFECTANTES COMO MESAS, MOBILIARIOS DE MEDICAMENTOS, ESTACION DE ENFERMERIA, DISPENSADORES DE PAPEL TOALLA E HIGIENICO'),
    ('Paso 13', 'SE ENJUAGA UNIDAD DE PACIENTE CON AGUA Y SE REALIZA METODO DE FRICCION CON WAYPALL'),
    ('Paso 14', 'SE REALIZA HIGIENE DE MANOS Y SE COLOCA EL EQUIPO DE PROTECCIÓN PERSONAL'),
    ('Paso 15', 'SE CLASIFICA EL AREA SEGUN EL TIPO DE LIMPIEZA PROFUNDA'),
    ('Paso 16', 'SE LIMPIA Y DESINFECTA CON AGUA ENJABONADA, CON WAYPALL EN METODO DE FRICCION Y ARRASTRE'),
    ('Paso 17', 'SE ENJUAGA CON AGUA Y SE REALIZA METODO DE FRICCION CON WAYPALL'),
    ('Paso 18', 'SE LIMPIA LAS SUPERFICIES HORIZONTALES DEBEMOS LIMPIARLOS CON UN PAÑO EMBEDIDO DE DESINFECTANTES COMO CAMAS, MOBILIARIOS DE MEDICAMENTOS, LAMPARAS')
) AS t(title, description);